#!/bin/bash
# Regenerates the golden oracle vectors used by the Monkey C unit tests.
#
# The vectors are the ground truth: every ported outgoing message must serialize to exactly
# these packet bytes (produced by jwoglom's cliparser oracle). Output is written to
# tests/golden_vectors.txt as `messageName|txId|packetHex[,packetHex...]` lines.
#
# Requires a JDK 14+ (the oracle jar is compiled for class version 58). On this machine:
#   JAVA=/opt/homebrew/opt/openjdk/bin/java
# and the prebuilt jar lives in the PumpX2Kit oracle submodule. Override via env if needed.
set -euo pipefail

JAVA="${JAVA:-/opt/homebrew/opt/openjdk/bin/java}"
# Defaults to a PumpX2Kit checkout sitting next to this repo; override with PUMPX2_ORACLE_JAR.
JAR="${PUMPX2_ORACLE_JAR:-$(cd "$(dirname "$0")/.." && pwd)/../PumpX2Kit/vendor/pumpx2-oracle/cliparser/build/libs/cliparser.jar}"
OUT="$(cd "$(dirname "$0")/.." && pwd)/tests/golden_vectors.txt"

# Shared signing constants — identical to PumpX2Kit's OracleParityTests so signed packets match.
PAIRING_CODE="6VeDeRAL5DCigGw2"
TIME_SINCE_RESET="461589180"

pkts() { # extract the "packets" JSON array as comma-joined hex
  "$JAVA" -jar "$JAR" encode "$@" 2>/dev/null \
    | python3 -c 'import sys,json;print(",".join(json.load(sys.stdin)["packets"]))'
}
pkts_signed() {
  PUMP_PAIRING_CODE="$PAIRING_CODE" PUMP_TIME_SINCE_RESET="$TIME_SINCE_RESET" pkts "$@"
}

{
  echo "# Generated by tools/gen_golden.sh — do not edit by hand."
  echo "# format: messageName|txId|packetHex[,packetHex...]"

  # ApiVersion
  echo "ApiVersionRequest|0|$(pkts 0 ApiVersionRequest '{}')"

  # Empty-cargo CURRENT_STATUS reads (txId 11, matching OracleParityTests)
  for m in ControlIQIOBRequest NonControlIQIOBRequest InsulinStatusRequest \
           CurrentBatteryV2Request CurrentBasalStatusRequest HomeScreenMirrorRequest \
           PumpVersionRequest TimeSinceResetRequest CurrentBolusStatusRequest \
           LastBolusStatusV2Request ControlIQInfoV2Request LastBGRequest \
           PumpGlobalsRequest PumpSettingsRequest BolusCalcDataSnapshotRequest \
           AlertStatusRequest AlarmStatusRequest MalfunctionStatusRequest \
           HistoryLogStatusRequest CGMAlertStatusRequest; do
    echo "$m|11|$(pkts 11 "$m" '{}')"
  done

  # Variable-cargo / multi-packet
  echo "HistoryLogRequest|8|$(pkts 8 HistoryLogRequest '[1000, 10]')"
  echo "CentralChallengeRequest|1|$(pkts 1 CentralChallengeRequest '{"appInstanceId":0,"centralChallenge":"00112233445566778899"}')"
  echo "PumpChallengeRequest|2|$(pkts 2 PumpChallengeRequest '{"appInstanceId":0,"pumpChallengeHash":"0102030405060708090a0b0c0d0e0f1011121314"}')"

  # JPAKE resume wire framing (rounds 3-4; full-pairing 1a/1b/2 are off-device, not tested here)
  echo "Jpake4KeyConfirmationRequest|6|$(pkts 6 Jpake4KeyConfirmationRequest '{"appInstanceId":0,"nonce":"0001020304050607","reserved":"0000000000000000","hashDigest":"6465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f80818283"}')"

  # Signed bolus flow
  echo "BolusPermissionRequest|0|$(pkts_signed 0 BolusPermissionRequest '{}')"
  echo "CancelBolusRequest|3|$(pkts_signed 3 CancelBolusRequest '[10650]')"
  echo "BolusPermissionReleaseRequest|4|$(pkts_signed 4 BolusPermissionReleaseRequest '[10650]')"
  echo "InitiateBolusRequest|9|$(pkts_signed 9 InitiateBolusRequest '[1000, 42, 1, 0, 0, 0, 0, 0]')"
  # DismissNotificationRequest via the raw-cargo (byte[]) ctor: notificationId 10, ALERT(1), action 0.
  echo "DismissNotificationRequest|5|$(pkts_signed 5 DismissNotificationRequest '["0a0000000100"]')"

  # --- Response frames (pump -> app), for ResponseParser tests. Encoded with known field values;
  # positional params match each response's Java constructor. Signed responses use the env above.
  echo "# responses below"
  echo "TimeSinceResetResponse|11|$(pkts 11 TimeSinceResetResponse '[461589180, 461589000]')"
  echo "ControlIQIOBResponse|11|$(pkts 11 ControlIQIOBResponse '[1500, 3600, 2000, 1234, 1]')"
  echo "CurrentBatteryV2Response|11|$(pkts 11 CurrentBatteryV2Response '[90, 75, 1, 0, 0, 0, 0]')"
  echo "InsulinStatusResponse|11|$(pkts 11 InsulinStatusResponse '[123, 0, 20]')"
  echo "CurrentBasalStatusResponse|11|$(pkts 11 CurrentBasalStatusResponse '[750, 750, 0]')"
  echo "CurrentEgvGuiDataV2Response|11|$(pkts 11 CurrentEgvGuiDataV2Response '[461589180, 120, 1, 5]')"
  echo "CurrentBolusStatusResponse|11|$(pkts 11 CurrentBolusStatusResponse '[1, 42, 1000, 5000, 0, 1]')"
  echo "LastBolusStatusV2Response|11|$(pkts 11 LastBolusStatusV2Response '[1, 42, 461589180, 1000, 0, 0, 1, 0, 1000]')"
  echo "BolusPermissionResponse|0|$(pkts_signed 0 BolusPermissionResponse '[0, 10650, 0]')"
  echo "InitiateBolusResponse|0|$(pkts_signed 0 InitiateBolusResponse '[0, 42, 1]')"
} > "$OUT"

echo "wrote $OUT"
cat "$OUT"
